<a href="https://colab.research.google.com/github/Pavancode-py/My-work-of-practice/blob/main/Business%20task%20DAY2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DATA ANALYSIS PROJECT ON ABSENTISM DATA.

In [80]:
# import packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing

LOAD THE DATA

In [81]:
data = pd.read_csv("Absenteeism_data.csv")
data.head()

   ID  Reason for Absence        Date  ...  Children  Pets  Absenteeism Time in Hours
0  11                  26  07/07/2015  ...         2     1                          4
1  36                   0  14/07/2015  ...         1     0                          0
2   3                  23  15/07/2015  ...         0     0                          2
3   7                   7  16/07/2015  ...         2     0                          4
4  11                  23  23/07/2015  ...         2     1                          2

[5 rows x 12 columns]

COPY THE DATA AND THEN DROP THE ID COLUMN

In [82]:
# copy the data and then drop the id column.

df = data.copy()
df.head()

   ID  Reason for Absence        Date  ...  Children  Pets  Absenteeism Time in Hours
0  11                  26  07/07/2015  ...         2     1                          4
1  36                   0  14/07/2015  ...         1     0                          0
2   3                  23  15/07/2015  ...         0     0                          2
3   7                   7  16/07/2015  ...         2     0                          4
4  11                  23  23/07/2015  ...         2     1                          2

[5 rows x 12 columns]

DROP ID

In [83]:
df.drop(['ID'],axis=1,inplace=True)
df.head()

   Reason for Absence        Date  ...  Pets  Absenteeism Time in Hours
0                  26  07/07/2015  ...     1                          4
1                   0  14/07/2015  ...     0                          0
2                  23  15/07/2015  ...     0                          2
3                   7  16/07/2015  ...     0                          4
4                  23  23/07/2015  ...     1                          2

[5 rows x 11 columns]

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Reason for Absence         700 non-null    int64
 1   Date                       700 non-null    object
 2   Transportation Expense     700 non-null    int64
 3   Distance to Work           700 non-null    int64
 4   Age                        700 non-null    int64
 5   Daily Work Load Average    700 non-null    float64
 6   Body Mass Index            700 non-null    int64
 7   Education                  700 non-null    int64
 8   Children                   700 non-null    int64
 9   Pets                       700 non-null    int64
 10  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int64(9), object(1)
memory usage: 60.3+ KB

TASK FIND THE ABSENTISM TIME FROM WORK. Dependent Variable is Absentism time from work and the remaining side columns and independent.

In [85]:
# reason for absence

df['Reason for Absence'].min()

0

In [86]:
df['Reason for Absence'].max()

28

In [87]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [88]:
sorted(df['Reason for Absence'].unique())

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(28)]

GET DUMMIES FOR REASON FOR ABSENCE

In [89]:
reason_columns = pd.get_dummies(df['Reason for Absence']).astype(int)
reason_columns

     0   1   2   3   4   5   6   7   8   9   10  11  ...  16  17  18  19  21  22  23  24  25  26  27  28
0     0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   1   0   0
1     1   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0
2     0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   0   0   0   0   0
3     0   0   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0
4     0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   0   0   0   0   0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
695   0   0   0   0   0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0   0   0   0   0
696   0   0   0   0   0   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0
697   0   0   0   0   0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0   0   0   0   0
698   0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   0   0   0   0   0
699   0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   1

[700 rows x 28 columns]

ADDING A COLUMN TO CHECK

In [90]:
reason_columns['check'] = reason_columns.sum(axis=1).astype(int)
reason_columns

     0  1  2  3  4  5  6  7  8  9  10  11  ...  17  18  19  21  22  23  24  25  26  27  28  check
0    0  0  0  0  0  0  0  0  0  0   0   0  ...   0   0   0   0   0   0   0   0   1   0   0      1
1    1  0  0  0  0  0  0  0  0  0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0      1
2    0  0  0  0  0  0  0  0  0  0   0   0  ...   0   0   0   0   0   1   0   0   0   0   0      1
3    0  0  0  0  0  0  0  1  0  0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0      1
4    0  0  0  0  0  0  0  0  0  0   0   0  ...   0   0   0   0   0   1   0   0   0   0   0      1
..  .. .. .. .. .. .. .. .. .. ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
695  0  0  0  0  0  0  0  0  0  0   1   0  ...   0   0   0   0   0   0   0   0   0   0   0      1
696  0  0  0  0  0  0  1  0  0  0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0      1
697  0  0  0  0  0  0  0  0  0  0   1   0  ...   0   0   0   0   0   0   0   0   0   0   0      1
698  0  0  0  0  0  0  0  0  0  0   0   0  ...   0   0   0   0   0   1   0   0   0   0   0      1
699  0  0  0  0  0  0  0  0  0  0   0   0  ...   0   0   0   0   0   0   0   0   0   0   1      1

[700 rows x 29 columns]

In [91]:
reason_columns.sum(axis=0)

0         38
1         16
2          1
3          1
4          2
5          3
6          6
7         13
8          5
9          4
10        22
11        24
12         8
13        52
14        18
15         2
16         3
17         1
18        21
19        36
21         6
22        32
23       147
24         3
25        29
26        31
27        66
28       110
check    700
dtype: int64

In [92]:
reason_columns['check'].unique()

array([1])

DROP CHECK column

In [93]:
reason_columns=reason_columns.drop(['check'],axis=1).astype(int)
reason_columns

     0   1   2   3   4   5   6   7   8   9   10  11  12  ...  15  16  17  18  19  21  22  23  24  25  26  27  28
0     0   0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   1   0   0
1     1   0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0   0
2     0   0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   1   0   0   0   0   0
3     0   0   0   0   0   0   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0   0
4     0   0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   1   0   0   0   0   0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
695   0   0   0   0   0   0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0   0
696   0   0   0   0   0   0   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0   0
697   0   0   0   0   0   0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0   0
698   0   0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   1   0   0   0   0   0
699   0   0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0   1

[700 rows x 28 columns]

In [94]:
reason_columns = pd.get_dummies(df['Reason for Absence'],drop_first=True).astype(int)
reason_columns

     1   2   3   4   5   6   7   8   9   10  11  12  ...  16  17  18  19  21  22  23  24  25  26  27  28
0     0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   1   0   0
1     0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0
2     0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   0   0   0   0   0
3     0   0   0   0   0   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0
4     0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   0   0   0   0   0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
695   0   0   0   0   0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0
696   0   0   0   0   0   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0
697   0   0   0   0   0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   0
698   0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   0   0   0   0   0
699   0   0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0   0   0   1

[700 rows x 27 columns]

GROUPS THE REASON FOR ABSENCE

In [95]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [96]:
reason_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28])

In [97]:
df=df.drop(['Reason for Absence'],axis=1)
df

           Date  Transportation Expense  ...  Pets  Absenteeism Time in Hours
0    07/07/2015                     289  ...     1                          4
1    14/07/2015                     118  ...     0                          0
2    15/07/2015                     179  ...     0                          2
3    16/07/2015                     279  ...     0                          4
4    23/07/2015                     289  ...     1                          2
..          ...                     ...  ...   ...                        ...
695  23/05/2018                     179  ...     0                          8
696  23/05/2018                     225  ...     2                          3
697  24/05/2018                     330  ...     0                          8
698  24/05/2018                     235  ...     0                          2
699  31/05/2018                     291  ...     1                          2

[700 rows x 10 columns]

In [98]:
reason_type1=reason_columns.loc[:,1:14].max(axis=1).astype(int)
reason_type2=reason_columns.loc[:,15:17].max(axis=1).astype(int)
reason_type3=reason_columns.loc[:,18:21].max(axis=1).astype(int)
reason_type4=reason_columns.loc[:,22:28].max(axis=1).astype(int)

In [103]:
reason_type4.astype(int)

0      1
1      0
2      1
3      0
4      1
      ..
695    0
696    0
697    0
698    1
699    1
Length: 700, dtype: int64

CONCAT THE COLUMN VALUES

In [100]:
df = pd.concat([df,reason_type1,reason_type2,reason_type3,reason_type4],axis=1)
df

           Date  Transportation Expense  Distance to Work  Age  ...  0  1  2  3
0    07/07/2015                     289                36   33  ...  0  0  0  1
1    14/07/2015                     118                13   50  ...  0  0  0  0
2    15/07/2015                     179                51   38  ...  0  0  0  1
3    16/07/2015                     279                 5   39  ...  1  0  0  0
4    23/07/2015                     289                36   33  ...  0  0  0  1
..          ...                     ...               ...  ...  ... .. .. .. ..
695  23/05/2018                     179                22   40  ...  1  0  0  0
696  23/05/2018                     225                26   28  ...  1  0  0  0
697  24/05/2018                     330                16   28  ...  1  0  0  0
698  24/05/2018                     235                16   32  ...  0  0  0  1
699  31/05/2018                     291                31   40  ...  0  0  0  1

[700 rows x 14 columns]

In [124]:
df.columns.values

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Date',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours'], dtype=object)

In [128]:
columns_names=['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason1', 'Reason2', 'Reason3', 'Reason4']

In [129]:
df.columns=columns_names

In [130]:
df.head()

         Date  Transportation Expense  Distance to Work  Age  ...  Reason1  Reason2  Reason3  Reason4
0  07/07/2015                     289                36   33  ...        0        0        0        1
1  14/07/2015                     118                13   50  ...        0        0        0        0
2  15/07/2015                     179                51   38  ...        0        0        0        1
3  16/07/2015                     279                 5   39  ...        1        0        0        0
4  23/07/2015                     289                36   33  ...        0        0        0        1

[5 rows x 14 columns]

In [131]:
columns_names_reordered = ['Reason1', 'Reason2', 'Reason3', 'Reason4','Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [132]:
df = df[columns_names_reordered]

In [133]:
df.head()

   Reason1  Reason2  Reason3  Reason4  ... Education  Children  Pets  Absenteeism Time in Hours
0        0        0        0        1  ...         1         2     1                          4
1        0        0        0        0  ...         1         1     0                          0
2        0        0        0        1  ...         1         0     0                          2
3        1        0        0        0  ...         1         2     0                          4
4        0        0        0        1  ...         1         2     1                          2

[5 rows x 14 columns]

In [167]:
df_reason_mod=df.copy()
df_reason_mod

     Reason1  Reason2  Reason3  Reason4  ... Education  Children  Pets  Absenteeism Time in Hours
0          0        0        0        1  ...         1         2     1                          4
1          0        0        0        0  ...         1         1     0                          0
2          0        0        0        1  ...         1         0     0                          2
3          1        0        0        0  ...         1         2     0                          4
4          0        0        0        1  ...         1         2     1                          2
..       ...      ...      ...      ...  ...       ...       ...   ...                        ...
695        1        0        0        0  ...         2         2     0                          8
696        1        0        0        0  ...         1         1     2                          3
697        1        0        0        0  ...         2         0     0                          8
698        0        0        0        1  ...         3         0     0                          2
699        0        0        0        1  ...         1         1     1                          2

[700 rows x 14 columns]

DEALING WITH DATE

In [168]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'],format= '%d/%m/%Y')
df_reason_mod['Date']

0     2015-07-07
1     2015-07-14
2     2015-07-15
3     2015-07-16
4     2015-07-23
         ...
695   2018-05-23
696   2018-05-23
697   2018-05-24
698   2018-05-24
699   2018-05-31
Name: Date, Length: 700, dtype: datetime64[ns]

In [169]:
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Reason1                    700 non-null    int64
 1   Reason2                    700 non-null    int64
 2   Reason3                    700 non-null    int64
 3   Reason4                    700 non-null    int64
 4   Date                       700 non-null    datetime64[ns]
 5   Transportation Expense     700 non-null    int64
 6   Distance to Work           700 non-null    int64
 7   Age                        700 non-null    int64
 8   Daily Work Load Average    700 non-null    float64
 9   Body Mass Index            700 non-null    int64
 10  Education                  700 non-null    int64
 11  Children                   700 non-null    int64
 12  Pets                       700 non-null    int64
 13  Absenteeism Time in Hours  700 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(12)
memory usage: 76.7 KB

Extract the Month values.

In [170]:
list_months = []
list_months

[]

In [171]:
for i in range(df_reason_mod.shape[0]):
  list_months.append(df_reason_mod['Date'][i].month)

In [173]:
len(list_months)

700

In [174]:
df_reason_mod['Month Value'] = list_months

In [175]:
df_reason_mod.head()

   Reason1  Reason2  Reason3  Reason4  ... Children  Pets  Absenteeism Time in Hours  Month Value
0        0        0        0        1  ...        2     1                          4            7
1        0        0        0        0  ...        1     0                          0            7
2        0        0        0        1  ...        0     0                          2            7
3        1        0        0        0  ...        2     0                          4            7
4        0        0        0        1  ...        2     1                          2            7

[5 rows x 15 columns]

EXTRACT THE DAY OF THE WEEK

In [176]:
def day_to_weekday(date_value):
    return date_value.weekday()

In [177]:
df_reason_mod['Day of the Week'] = df_reason_mod['Date'].apply(day_to_weekday)
df_reason_mod.head()

   Reason1  Reason2  Reason3  ...  Absenteeism Time in Hours Month Value  Day of the Week
0        0        0        0  ...                          4           7                1
1        0        0        0  ...                          0           7                1
2        0        0        0  ...                          2           7                2
3        1        0        0  ...                          4           7                3
4        0        0        0  ...                          2           7                3

[5 rows x 16 columns]